### ISSUE TITLE
Tractor mode on remote PC

### ISSUE THREAD

**Issue by hm-sarah** [StanleyInnovation/segway_v3#12]
Hi, we are trying to control the Segway from a remote PC, 
but we are unable to put the Segway in Tractor mode to control it from the remote PC in RViz.
(we can put it in tractor mode from the PC on board and we can control it with a joystick, but we need to do it from the remote PC)
Thanks.

**Comment by PatrickHussey** [comment]
You likely have the network configuration on the remote PC set incorrectly

find 50.segway_network_config.sh in the workspace (segway_ws/devel/etc/catkin/profile.d if you already compiled; or in the package segway_v3_network but you'll have to delete the build/devel dirs and recompile)

and make sure you have

```
export ROBOT_NETWORK=eth0 #or whatever NIC or WLAN your using
export ROS_IP=$(ip -4 address show $ROBOT_NETWORK | grep 'inet' | sed 's/.*inet \([0-9\.]\+\).*/\1/')
export ROS_MASTER_URI=http://10.66.171.4:11311/ #this is the IP of the onboard PC
```

Also if you are using a VM make sure the virtual network interface is BRIDGED and not NAT

**Comment by PatrickHussey** [comment]
did this get resolved?
