### ISSUE TITLE
SLAM Gmapping demo Issue

### ISSUE THREAD

**Issue by aswinsarang** [StanleyInnovation/segway_v3#14]
![stan](https://cloud.githubusercontent.com/assets/20059079/19389100/9f73e8b0-9233-11e6-9ca3-6c8b0897612f.png)

What  is the workaround for this error?

**Comment by PatrickHussey** [comment]
It looks like a memory corruption issue, likely caused by the laser scan being in the wrong format. Since we did not integrate the laser for you I am not sure what might be causing it. Take a close look at the entire chain of how the data feeding gmapping gets generated.
