### ISSUE TITLE
Could not start RMP communication stream

### ISSUE THREAD

**Issue by cangjiaxaun** [StanleyInnovation/segway_v3#15]
Hi, ther I meet a problem while starting the driver node called "Could not start RMP communication stream"
First we tried to launch the program without the arms.
I rename the /usr/sbin/segway_core_start. So I can run this program in the terminal. I also tried roslaunch segway_bringup stanley_innovation_system.launch without run the "segway_core_start" program. 
Here is the screen shot when I run the program in the terminal:
![error1](https://cloud.githubusercontent.com/assets/15178808/19393725/954c21ec-9268-11e6-8d56-bf94c39b257a.png)
![error2](https://cloud.githubusercontent.com/assets/15178808/19393731/9680f06a-9268-11e6-93bb-d2e8f7df0f7b.png)
![error3](https://cloud.githubusercontent.com/assets/15178808/19393732/9875b4d2-9268-11e6-9050-66b9096a689d.png)

I think we have the third error because the first one, that is the communication problem.
And I got a new warning message as shown in the following pic, all the other error messages are the same.
![img-20161014-wa0029](https://cloud.githubusercontent.com/assets/15178808/19393740/a3b65c66-9268-11e6-987d-72873aa03c01.jpg)

Plus, we tried to run the program with the arm connected
And I got the same warning message as above(but appear in a different place) as shown in the following picture, and all other error messages are the same
![error4](https://cloud.githubusercontent.com/assets/15178808/19393735/9c89f100-9268-11e6-8cca-dc57d22d6e25.png)

------------------------------------------------------------------------------------------------------------
I tried to ping 10.66.171.5 and 10.66.171.4, both are success. And all the echo return the right result. Would you please help me with my problem? Thanks in advance!

**Comment by PatrickHussey** [comment]
This is due to an incompatibility between the embedded firmware and the ROS drivers being used in most cases.

Have you updated either recently, can you please describe what has changed since it was last working?

**Comment by cangjiaxaun** [comment]
I have update my firmware recently.

**Comment by PatrickHussey** [comment]
You'll need to be careful because you have a custom setup. I'll send you the list of packages you'll need to replace in a minute. 

Please make a backup of the onboard PC and a backup copy of the workspace in the home directory.

**Comment by cangjiaxaun** [comment]
Seems very complicate, could I just rollback my firmware?

**Comment by PatrickHussey** [comment]
You can do that, I can send a copy of the original firmware your machine was delivered with.

**Comment by cangjiaxaun** [comment]
I recalled that I update the firmware because my UI box is broken and I sent my UI box to stanley company to repair it, and we cannot charge our battery without updating the firmware. So maybe I should  choose the hard way

**Comment by PatrickHussey** [comment]
The firmware does not have anything to do with charging, only the communication interface and operation. I know you have custom balancing gains that we tuned so a rollback might be the safest option. 

The platform should perform as it did before we did the repair for you with the firmware rolled back.

**Comment by PatrickHussey** [comment]
This is one of the platforms that you received from Gaitech, correct?

**Comment by cangjiaxaun** [comment]
Yes....

**Comment by cangjiaxaun** [comment]
Please send me the original firmware so I could do the rollback, should I provide my e-mail address here?

**Comment by PatrickHussey** [comment]
Here is the original embedded firmware for your machine. 
[gaitech_firmware.zip](https://github.com/StanleyInnovation/segway_v3/files/529995/gaitech_firmware.zip)

**Comment by cangjiaxaun** [comment]
Thank you, should I follow the instruction at here?
https://github.com/StanleyInnovation/segway_v3_embedded_firmware

**Comment by PatrickHussey** [comment]
No need, please let me know when you have downloaded the attachment. I want to remove it from this thread so that someone else doesn't accidentally load it on a different machine.

**Comment by PatrickHussey** [comment]
Yes please follow those instructions

**Comment by cangjiaxaun** [comment]
I have download it and I will do the rollback now.

**Comment by PatrickHussey** [comment]
Thanks, let me know that you are all set once you've performed the update.

**Comment by cangjiaxaun** [comment]
Hi I have successfully update the firmware and boot the system. Now I'm trying to control the platform with Logitech joystick.

**Comment by PatrickHussey** [comment]
So the driver launches correctly and everything now?

**Comment by cangjiaxaun** [comment]
Yes the driver launches perfectly now!

**Comment by PatrickHussey** [comment]
Great, glad to get you up and running again! 

Closing this issue

**Comment by cangjiaxaun** [comment]
Thank you very much for your help!
