### ISSUE TITLE
Typos in segway_ros/segway_test_balancing

### ISSUE THREAD

**Issue by tyunist** [StanleyInnovation/segway_v3#2]
1. Line 10: 
rosrun vector_ros segway_test_balancing should be 
rosrun segway_ros segway_test_balancing
2. Line 78:
from from segway.system_defines import *      should be 
from segway.system_defines import *
3. Line 91:
 client= Client("/segway",timeout=1.0)       should be 
 client= Client("/segway/segway_driver",timeout=1.0)

**Comment by PatrickHussey** [comment]
Thanks I've updated it and will push the changes once I've tested it. Sorry for the errors, I figured it would be best to get an example up rather than wait to test on hardware.

Thanks for posting
