### ISSUE TITLE
segway_driver: only connects to base when it uses the same interface as $ROS_IP

### ISSUE THREAD

**Issue by jack-oquin** [StanleyInnovation/segway_v3#20]
In ``io_eth.py``, the ``IoEthThread`` class ``__init__()`` method assumes the device and ``$ROS_IP`` are on the same interface:
```py
    self.conn.bind((os.environ['ROS_IP'],self.remote_address[1]))
    self.conn.connect(self.remote_address)
```
The ``bind()`` fails if they are on different interfaces. In our system, ``$ROS_IP`` refers to the wlan, while the segway base is on a hard-wired ethernet port.

Our current work-around is to define yet another environment variable giving the IP of the local host on the correct interface. Ideally, the driver should figure out what address to use from the route tables, but I am not sure how best to accomplish that. There is a Python route2 package available in Pypy, and available as a Debian package in Xenial, but not for Trusty.

cc: @piyushk

**Comment by jack-oquin** [comment]
As an experiment, I tried setting the first half of the ``bind()`` tuple to an empty string, and that appears to work on our system:
```py
    self.conn.bind(('', self.remote_address[1]))
```

**Comment by PatrickHussey** [comment]
Was just about to suggest that

**Comment by PatrickHussey** [comment]
I will update and commit with some other changes tonight or tomorrow

**Comment by jack-oquin** [comment]
Thanks!

**Comment by jack-oquin** [comment]
@PatrickHussey: I'd be happy to submit a PR for this, if you like.

**Comment by PatrickHussey** [comment]
Sorry the other changes are much larger and taking a while to test but I just committed this change

**Comment by jack-oquin** [comment]
No problem. Thanks, again!
