### ISSUE TITLE
CMAKE error

### ISSUE THREAD

**Issue by aswinsarang** [StanleyInnovation/segway_v3#24]
![screenshot from 2016-10-29 04 50 53](https://cloud.githubusercontent.com/assets/20059079/19828458/10c7847a-9d94-11e6-95a6-a58c432d9118.png)

**Comment by PatrickHussey** [comment]
Not sure you have the ROS dependencies installed. Based on the si@SIDEV1 tag on the prompt it's a different PC than the one we setup (sibot@SIBOT1). So you probably just need to install all the dependencies.
