### ISSUE TITLE
gmapping error

### ISSUE THREAD

**Issue by aswinsarang** [StanleyInnovation/segway_v3#25]
![stan](https://cloud.githubusercontent.com/assets/20059079/19829856/c6d6277c-9dfc-11e6-8715-5669391e4e6d.png)

workaround?

**Comment by PatrickHussey** [comment]
It looks like a memory corruption issue, likely caused by the laser scan message being in the wrong format. Since we did not integrate the laser for you I am not sure what might be causing it. Take a close look at the entire chain of how the data feeding gmapping gets generated.

The platform driver supplies the odom->base_link transform and the odometry topic; the only other thing you need is a valid laser_scan topic in the base_link frame published on the /segway/filtered_scan topic.

**Comment by aswinsarang** [comment]
![error](https://cloud.githubusercontent.com/assets/20059079/19845722/00077a6c-9f53-11e6-88c4-745a23731ba5.png)

Anything to do with this?

**Comment by aswinsarang** [comment]
![screenshot from 2016-10-31 10 30 31](https://cloud.githubusercontent.com/assets/20059079/19845938/1c0e73bc-9f55-11e6-882d-ee9f4d96519d.png)

We are using a velodyne vlp 16 for slam. Thats the only lidar mounted on segway at the moment. No other laser.

Correct me if I am wrong, the topic has to be **/velodyne_points** instead of **/segway/filtered_scan** ?

![screenshot from 2016-10-31 10 30 31](https://cloud.githubusercontent.com/assets/20059079/19846093/f98e43d4-9f55-11e6-8bef-5c50b5912252.png)

**Comment by aswinsarang** [comment]
@PatrickHussey This is the content inside the configuration file. No other laser except for velodyne.
`# This configures the environment variables for a segway rmp V3 simulation
# This is necessary to run before starting the simulation 
#

# If there is an onboard PC powered by the system this will run the watchdog
# to make sure it gets gracefully shutdown before the system power cuts out.
export SEGWAY_POWERS_PC_ONBOARD=true

#Default Segway RMP_V3 network 
export SEGWAY_IP_ADDRESS=10.66.171.5
export SEGWAY_IP_PORT_NUM=8080

# The reference frame for all the accessories and sensors
export SEGWAY_PARENT_LINK=base_chassis_link

#Determines if move base should run in balance mode, if false runs in tractor
export SEGWAY_RUNS_IN_BALANCE_MODE=false
# Determines if Segway platform is equipped with a BSA almost all are expect the RMP210
export SEGWAY_HAS_BSA=true

# Platform name for specific URDF models and configurations; the base platform is
# used for drivers, sim controllers, etc; the platform name is for special URDF/Sensor
# configurations. In general they should be the same unless we built you a custom system
export SEGWAY_BASE_PLATFORM=RMP_220
export SEGWAY_PLATFORM_NAME=RMP_220
export SEGWAY_IS_OMNI=false

# Defines the location of the sensors frames and the UI box
# they all move together for the navigator elite. This is the point at the
# base of the sensor pedestal aligned with the base_link
export NAVIGATOR_ELITE_XYZ="-0.1801 0 0.060625"

#Only the RMP220 and RMP210 can have caster plates so do not enable them if using another model
export SEGWAY_HAS_REAR_CASTER=true
export SEGWAY_HAS_FRONT_CASTER=true

#Determines if the platform should use 2D or 3D odometry
export SEGWAY_USE_2D_ODOMETRY=true
# Determines if we should use robot_localization EKF or the onboard odometry;
# set to true for onboard odometry
export SEGWAY_USE_PLATFORM_ODOMETRY=true
# determines if GPS is used for local or global odometry (requires a GPS data source)
export SEGWAY_USE_GPS_FOR_LOCAL_ODOM=false
export SEGWAY_USE_GPS_FOR_GLOBAL_LOCALIZATION=false

# Joystick configurations for onboard joystick
# Joystick configurations for onboard joystick
export SEGWAY_HAS_ONBOARD_JOY=true
export SEGWAY_JOY_DEV=/dev/input/js0
export SEGWAY_JOY_MAPPING=xbox360
export SEGWAY_JOY_DEADZONE=0.1

# Sets whether the costmaps use 3D voxel grid layer (need a 3D sensor enabled)
export SEGWAY_USE_VOXEL_GRID=true

# External IMU configuration;
export SEGWAY_HAS_EXT_IMU=false
export SEGWAY_HAS_UM7_IMU=false
export SEGWAY_UM7_DEV="/dev/serial/by-path/pci-0000:00:14.0-usb-0:3:1.0-port0"
export EXT_IMU_XYZ="-0.25203 0.130 0.0715"
export EXT_IMU_RPY="3.1415 0 3.1415"

# GPS configuration
export SEGWAY_HAS_GPS=false
export SEGWAY_HAS_NEO7=false
export SEGWAY_NEO7_DEV="/dev/serial/by-path/pci-0000:00:14.0-usb-0:4:1.0-port0"
export GPS_XYZ="0.5 0 0.25409"
export GPS_RPY="0 0 0"

# 2D scanner configuration for launch files; should change hokuyo
# to sick if using a SICK LMS1XX
export SEGWAY_HAS_ONE_2D_LASER=false
export SEGWAY_HAS_SECOND_2D_LASER=false

# Hokuyo configuration (only supports two by default) watch 
# wavelength on multi-laser systems
export SEGWAY_LASER1_IS_HOKUYO=false
export SEGWAY_LASER1_IS_SICK_TIM=false
export SEGWAY_LASER1_IP=10.66.171.8
export SEGWAY_LASER1_PORT=2112
#Uncomment below and comment line above for hokuyo
#export SEGWAY_LASER1_PORT=10940 
export LASER1_XYZ="0.62204 0 0.25409"
export LASER1_RPY="0 0 0"
export LASER1_MAX_RANGE=20.0
export LASER1_MIN_RANGE=0.01
export LASER1_PREFIX="front"

export SEGWAY_LASER2_IS_HOKUYO=false
export SEGWAY_LASER2_IS_SICK_TIM=false
export SEGWAY_LASER2_IP=10.66.171.9
export SEGWAY_LASER2_PORT=2112
#Uncomment below and comment line above for hokuyo
#export SEGWAY_LASER1_PORT=10940 
export LASER2_XYZ="-0.62204 0 0.25409"
export LASER2_RPY="0 0 3.1415"
export LASER2_MAX_RANGE=20.0
export LASER2_MIN_RANGE=0.01
export LASER2_PREFIX="rear"

# Segway has KINECT
export SEGWAY_HAS_KINECT=false
export SEGWAY_HAS_KINECT_360=false
#export SEGWAY_HAS_KINECT_ONE=false not supported unless custom platform
export RGBD_SENSOR_XYZ="0 0 1.0"
export RGBD_SENSOR_RPY="0 0 0"

# Segway has VLP16
export SEGWAY_HAS_VLP16=true
export SEGWAY_VLP16_IP=192.168.1.201
export SEGWAY_VLP16_PORT=2368
export VLP16_XYZ="0 0 1.15"
export VLP16_RPY="0 0 0"

# Machine vision
export SEGWAY_HAS_FLEA3=false
export SEGWAY_FLEA3_SN='14472220'
export SEGWAY_FLEA3_IS_CALIBRATED=false
export FLEA3_XYZ="0.0518 0 0.35508750"
export FLEA3_RPY="0 0 0"`

**Comment by aswinsarang** [comment]
@PatrickHussey Attaching the config file for reference.
[segway_config.txt](https://github.com/StanleyInnovation/segway_v3/files/561215/segway_config.txt)

**Comment by aswinsarang** [comment]
Update 
![new update](https://cloud.githubusercontent.com/assets/20059079/19847510/d6351a88-9f60-11e6-8923-0f3362383344.png)

when I set the topic to **/segway/scan** I was able to obtain a portion of the poincloud. Will this help in gmapping?

**Comment by aswinsarang** [comment]
issue resolved
