### ISSUE TITLE
Segway power button

### ISSUE THREAD

**Issue by hm-sarah** [StanleyInnovation/segway_v3#27]
Hello,
We would like to find a way to power the segway base without pushing the power button.
Is there a recommendation or a suggestion for a way to power the base externally? (we need to extend the power button for an external access),
Thanks

**Comment by PatrickHussey** [comment]
The only other way to start the system is by connecting 5V to the USB input temporarily. The system should boot and then USB power should be removed so the system is able to shut itself down normally.

**Comment by hm-sarah** [comment]
Dear Patrick, 
Thanks, this was helpful.
Is there a way to power down the segway without pushing the power button or the emergency button?

**Comment by PatrickHussey** [comment]
You can publish a message to the topic /segway/gp_command here is an example in python:

```
#!/usr/bin/env python

from segway_msgs.msg import ConfigCmd
from segway.system_defines import *
import rospy

if __name__=="__main__":
    rospy.init_node("segway_shutdown") 
    gp_pub = rospy.Publisher("/segway/gp_command",ConfigCmd,queue_size=10)

    mode_cmd = ConfigCmd()
    mode_cmd.header.stamp = rospy.get_rostime()
    mode_cmd.gp_cmd = "GENERAL_PURPOSE_CMD_SET_OPERATIONAL_MODE"
    mode_cmd.gp_param = 2 #This is POWERDOWN_REQUEST from system_defines.py
    
    gp_pub.publish(mode_cmd)
    rospy.spin() 
```

**Comment by PatrickHussey** [comment]
or press the start button (I believe) on the joystick if you're using a logitech F310 or F710

**Comment by PatrickHussey** [comment]
closing old topic
