### ISSUE TITLE
Equip Segway V3 RMP 220 with two Kinova Arms

### ISSUE THREAD

**Issue by tyunist** [StanleyInnovation/segway_v3#3]
As it says in the Manual (page 42, Power), the segway comes with an optional Power Converter to supply auxiliary equipment. However, I guess that my Segway does not have such Power Converter as the following image shows. 
https://drive.google.com/file/d/0B5KigBffI1k8aGU4bXV5SGxRV0sxS2d2a1d2cEp3d3pmTGRV/view?usp=sharing

Indeed, we'd like to equip the Segway with[ two Kinova robot arms](https://www.google.co.kr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwi39oW23sTLAhXDMKYKHWWdAUoQjRwIBw&url=http%3A%2F%2Fwww.authenticwatchesebay.com%2Fadd-to-compare-c-1350_1370_1377_1378_1379%2Fkinova-jaco-robot-manipulator-research-edition-p-15112.html&psig=AFQjCNETlGBI-gZZAHMd7LXAlq-fZgX8bQ&ust=1458201600989920).

Each arm consumes in average 25 W (100 W at peak) and requires a 24V input. In total, we may need two 24V outputs from the harness for Connector I. Could you please suggest me how to change the current configuration to support two such 24V arms? 

Thanks,

**Comment by PatrickHussey** [comment]
You will need two 24V DC-DC converters. By default the system comes with one 12V converter, and can support one additional. To support two we need to do a modification to the UI harnessing and add a special mounting plate.

Additional DC-DC converters for powering peripherals are optional when specifying your order. They can be added after, but this must be done by Stanley or Segway to avoid invalidating your warranty.

Please contact sales (info@stanleyinnovation.com) and they will give you a quote and details on how to ship your UI box back to be upgraded.
