### ISSUE TITLE
roslaunch segway_bringup stanley_innovation_system.launch runtime erro

### ISSUE THREAD

**Issue by YuehChuan** [StanleyInnovation/segway_v3#31]
Hi, I got segwayR220 and followed the steps mentioned here 
https://github.com/StanleyInnovation/segway_v3_robot
this is history:
https://hackmd.io/s/BykpsJ2_b#
The segway is not from stanley source
and we found that 
inside segway ip is 192.168.0.40

when i try `roslaunch segway_bringup stanley_innovation_system.launch `
got run time error
![segway](https://user-images.githubusercontent.com/7314531/29653181-66213cee-88db-11e7-8a11-afcbf956bab8.png)
![segway2](https://user-images.githubusercontent.com/7314531/29653182-6642fc30-88db-11e7-8d73-0c0222d21d21.png)

How could I set ROS_MASTER_URI inside segway?

thank you in advance

**Comment by PatrickHussey** [comment]
If the RMP was not purchased through Stanley Innovation, none of the ROS code in our repos will be compatible.

**Comment by YuehChuan** [comment]
It's a humble ROS driver  implementation for RMP220 not purchased through Stanley Innovation.  Welcome further  improvement or suggestions.
https://github.com/YuehChuan/rmp220-segway-nvision  
I close the issue now.
