### ISSUE TITLE
Connecting robot computer to internet

### ISSUE THREAD

**Issue by wuisiong** [StanleyInnovation/segway_v3#5]
Plugging in the RJ-45 cable on the robot to a network wall socket does not work due to static IPs. However, it doesn't make sense to change the IP addresses of the router and pc if I want to connect to an external network.

In your quick start for two computers, under networking 10.1.1, you mentioned that to connect to the internet, I'd have to setup a bridge from my connection to the internal wireless network.

Can you kindly elaborate on that?

**Comment by PatrickHussey** [comment]
You can use one of the lan ports (furthest to the right on the front) to connect to the Internet with DHCP. The other 5 ports are bridged to a static IP for the robot network.
